const airports = [
  {
    id: 1,
    name: "John F. Kennedy International Airport",
    code: "JFK",
    creationDate: "2024-04-15",
    city: "New York",
    numberOfPassengers: 65000000,
    destination: ["Los Angeles", "Chicago", "Miami"],
  },
  {
    id: 2,
    name: "Heathrow Airport",
    code: "LHR",
    creationDate: "2024-04-16",
    city: "London",
    numberOfPassengers: 80000000,
    destination: ["Paris", "Berlin", "Rome"],
  },
  {
    id: 3,
    name: "Narita International Airport",
    code: "NRT",
    creationDate: "2024-04-17",
    city: "Tokyo",
    numberOfPassengers: 45000000,
    destination: ["Beijing", "Seoul", "Sydney"],
  },
  {
    id: 4,
    name: "Dubai International Airport",
    code: "DXB",
    creationDate: "2024-04-18",
    city: "Dubai",
    numberOfPassengers: 100000000,
    destination: ["Istanbul", "Moscow", "Cairo"],
  },
  {
    id: 5,
    name: "Guarulhos–Governador André Franco Montoro International Airport",
    code: "GRU",
    creationDate: "2024-04-19",
    city: "São Paulo",
    numberOfPassengers: 70000000,
    destination: ["Rio de Janeiro", "Buenos Aires", "Lima"],
  },
  {
    id: 6,
    name: "Los Angeles International Airport",
    code: "LAX",
    creationDate: "2024-04-20",
    city: "Los Angeles",
    numberOfPassengers: 60000000,
    destination: ["New York", "San Francisco", "Las Vegas"],
  },
  {
    id: 7,
    name: "Charles de Gaulle Airport",
    code: "CDG",
    creationDate: "2024-04-21",
    city: "Paris",
    numberOfPassengers: 72000000,
    destination: ["London", "Berlin", "Madrid"],
  },
  {
    id: 8,
    name: "Frankfurt Airport",
    code: "FRA",
    creationDate: "2024-04-22",
    city: "Frankfurt",
    numberOfPassengers: 65000000,
    destination: ["London", "Paris", "Amsterdam"],
  },
  {
    id: 9,
    name: "Changi Airport",
    code: "SIN",
    creationDate: "2024-04-23",
    city: "Singapore",
    numberOfPassengers: 68000000,
    destination: ["Bangkok", "Kuala Lumpur", "Hong Kong"],
  },
  {
    id: 10,
    name: "Hartsfield–Jackson Atlanta International Airport",
    code: "ATL",
    creationDate: "2024-04-24",
    city: "Atlanta",
    numberOfPassengers: 90000000,
    destination: ["New York", "Miami", "Chicago"],
  },
  {
    id: 11,
    name: "Denver International Airport",
    code: "DEN",
    creationDate: "2024-04-25",
    city: "Denver",
    numberOfPassengers: 55000000,
    destination: ["Los Angeles", "Chicago", "Dallas"],
  },
  {
    id: 12,
    name: "Beijing Capital International Airport",
    code: "PEK",
    creationDate: "2024-04-26",
    city: "Beijing",
    numberOfPassengers: 110000000,
    destination: ["Shanghai", "Tokyo", "Seoul"],
  },
  {
    id: 13,
    name: "Sydney Airport",
    code: "SYD",
    creationDate: "2024-04-27",
    city: "Sydney",
    numberOfPassengers: 55000000,
    destination: ["Melbourne", "Brisbane", "Auckland"],
  },
  {
    id: 14,
    name: "Toronto Pearson International Airport",
    code: "YYZ",
    creationDate: "2024-04-28",
    city: "Toronto",
    numberOfPassengers: 60000000,
    destination: ["New York", "London", "Chicago"],
  },
  {
    id: 15,
    name: "Munich Airport",
    code: "MUC",
    creationDate: "2024-04-29",
    city: "Munich",
    numberOfPassengers: 60000000,
    destination: ["Frankfurt", "Berlin", "Vienna"],
  },
  {
    id: 16,
    name: "Hong Kong International Airport",
    code: "HKG",
    creationDate: "2024-04-30",
    city: "Hong Kong",
    numberOfPassengers: 68000000,
    destination: ["Bangkok", "Singapore", "Seoul"],
  },
  {
    id: 17,
    name: "Amsterdam Airport Schiphol",
    code: "AMS",
    creationDate: "2024-05-01",
    city: "Amsterdam",
    numberOfPassengers: 72000000,
    destination: ["London", "Paris", "Frankfurt"],
  },
  {
    id: 18,
    name: "McCarran International Airport",
    code: "LAS",
    creationDate: "2024-05-02",
    city: "Las Vegas",
    numberOfPassengers: 50000000,
    destination: ["Los Angeles", "New York", "San Francisco"],
  },
  {
    id: 19,
    name: "Adolfo Suárez Madrid–Barajas Airport",
    code: "MAD",
    creationDate: "2024-05-03",
    city: "Madrid",
    numberOfPassengers: 60000000,
    destination: ["Paris", "London", "Rome"],
  },
  {
    id: 20,
    name: "Suvarnabhumi Airport",
    code: "BKK",
    creationDate: "2024-05-04",
    city: "Bangkok",
    numberOfPassengers: 75000000,
    destination: ["Singapore", "Hong Kong", "Kuala Lumpur"],
  },
];

module.exports = airports;
